
---
- name: Pull MySQL image
  community.docker.docker_image:
    name: mysql
    source: pull

- name: Run MySQL container
  community.docker.docker_container:
    name: mysql_db
    image: mysql
    state: started
    restart_policy: always
    ports:
      - "{{ mysql_port }}:3306"
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: "{{ mysql_database }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
